[40기 - 윤형준] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/40-backend-westagram-1 pull request #11
Opened 2022-11-26 13:05 UTC by hysy9255

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- API Express 초기 설정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- /ping 앤드 포인트에서 Get request 시 "{message:pong}" 반환으로 응답하게 구현
- 서버 가동 코드 작성
- TypeORM을 통해 MySQL DB와 연동

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-26 13:06 UTC, hysy9255 commented
branch 명을 슬랙에 공지 해주신대로 수정하였더니 기존에 있던 pull request는 closed되었습니다.

2022-11-27 08:35 UTC, sangwoong03 requested changes

2022-11-27 08:35 UTC, sangwoong03 commented on hyungjoonYoon/app.js
> +// --
불필요한 주석은 삭제해주세요!

2022-11-27 08:35 UTC, sangwoong03 commented on hyungjoonYoon/db/schema.sql
> +
schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

`git rm --cached "file-name"` 에 대한 명령어를 학습하고 적용해주세요!

2022-11-28 03:33 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-28 03:33 UTC, merged