[40기 박진주] Assignment 3-8 CRUD 구현하기
wecode-bootcamp-korea/40-backend-westagram-1 pull request #14
Opened 2022-11-28 06:54 UTC by lolo-park

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- Assignment 3-8 CRUD 구현하기 업로드
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 게시글 등록하기
- 전체 게시글 조회 api 구현
- 특정 유저의 게시글 조회 api 구현
- 게시글 수정 api 구현
- 게시글 삭제 api 구현
- 좋아요 api 구현 

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-29 01:26 UTC, sangwoong03 requested changes
진주님! 크게 리뷰할 사항은 없어보입니다.

1. app.js 변수명 convention : camel case로 수정
2. raw-query 데이터 주입 방식 통일
3. migration 파일 기존의 파일로 대체 (2번 과제에서 수정한 내역이 포함될 수 있게끔)
4. 컨플릭트 해결

이해가 잘 되지 않으면 리뷰 남겨주세요~!

2022-11-29 01:26 UTC, sangwoong03 commented on ParkJInjoo/dd/my data sample.txt
> +
진주님! 불필요한 파일이 같이 올라온 것 같네요! 삭제 후 다시 Push 해주세요~!

2022-11-29 01:26 UTC, sangwoong03 commented on ParkJInjoo/db/schema.sql
> +
해당 파일도 `.gitignore`에 적용되기 이전에 push 되어 이력이 남아있는 것 같네요! 삭제해주세요!

`git rm --cached "file-name"`

2022-11-29 01:26 UTC, sangwoong03 commented on ParkJInjoo/app.js
> +  const { name, email, profile_image, password } = req.body;
실제 컬럼은 profile_image라고 명시되어 있지만, JavaScript 언어의 네이밍 컨벤션은 보통 Camel case로 작성합니다.

데이터베이스의 컬럼명이 아닌, 클라이언트로부터 요청 데이터를 받아오는 부분들 모두 Camel case로 수정해주세요!

```suggestion
  const { name, email, profileImage, password } = req.body;
```

2022-11-29 01:26 UTC, sangwoong03 commented on ParkJInjoo/app.js
> +    WHERE p.user_id = ${userId}
현재 데이터를 주입하는 방법이 작성해주신 api마다 다릅니다!

한가지 방식으로 통일해주세요!

Node.js에서 mysql driver를 사용하여 Raw SQL Query를 작성할 때 ?를 왜 사용하는지 한번 구글링하여 찾아보시면 좋을 것 같습니다.

2022-11-30 01:19 UTC, sangwoong03 requested changes

2022-11-30 01:19 UTC, sangwoong03 commented on ParkJInjoo/db/schema.sql
> +
진주님 아직 해당 부분 반영이 안된 것 같습니다!

2022-11-30 01:19 UTC, sangwoong03 commented on ParkJInjoo/dd/my data sample.txt
> +
진주님 해당 파일은 불필요한 파일처럼 보입니다. 삭제하고 다시 push 해주세요~!

2022-12-01 13:27 UTC, lolo-park commented
<img width="300" alt="스크린샷 2022-12-01 오후 10 22 09" src="https://user-images.githubusercontent.com/117656236/205063676-87dd0a03-55c1-413f-873b-8e445de65cb9.png">
멘토님, 불필요한 파일 삭제 하여 다시 push 하였는데 생각해보니 
assignment 1,2 하던 당시의 database 와 현재 database 가 다릅니다. 

중간에 문제가 생기면서 제가 기존에 만들었던 database를 지우고 새로 생성했었습니다. 
(table도 다시 만들고, 데이터들도 다시 새로 넣었었습니다) 
이 db 폴더를 merge 하고 기존에 merge 된 db 폴더를 삭제하는 것이 될까요?

2022-12-02 00:40 UTC, sangwoong03 commented
> 멘토님, 불필요한 파일 삭제 하여 다시 push 하였는데 생각해보니 assignment 1,2 하던 당시의 database 와 현재 database 가 다릅니다.
중간에 문제가 생기면서 제가 기존에 만들었던 database를 지우고 새로 생성했었습니다.
(table도 다시 만들고, 데이터들도 다시 새로 넣었었습니다)
이 db 폴더를 merge 하고 기존에 merge 된 db 폴더를 삭제하는 것이 될까요?


진주님 database가 달라짐에 따라 merge가 이루어지면서 수정된 migration 파일로 merge가 될 것입니다.
지금은 과제를 진행하면서 코드를 git으로 관리하지 않고 수동으로 관리하였기 때문에 버전관리가 안됐을 것입니다.
1, 2의 데이터베이스와 현재의 데이터 베이스는 다른 것이 맞는 현상이구요, 현재 PR이 merge될 때 최종적으로 변경된 데이터베이스 마이그레이션 파일이 반영이 되는 것입니다.

따라서 진주님께서 이번 PR에서 최종적으로 수정해야되는 부분을 수정하여 push해주시면 됩니다.

그 수정사항이 반영되기 위해 우리는 local의 main과 remote main의 버전 상태를 일치시켜주는 행위를 하는 것입니다.

2022-12-02 00:43 UTC, sangwoong03 requested changes

2022-12-02 00:43 UTC, sangwoong03 commented on ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
> +>>>>>>> 1cbc1d8fff979e9fb03058b6b4c3ed6b5f01d32d:ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
병합이 진행되면서 불필요한 코드가 추가된 것 같습니다. 삭제해주세요!

2022-12-02 00:43 UTC, sangwoong03 commented on ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
> +=======
병합이 진행되면서 불필요한 코드가 추가된 것 같습니다. 삭제해주세요!

2022-12-02 00:43 UTC, sangwoong03 commented on ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
> +>>>>>>> 1cbc1d8fff979e9fb03058b6b4c3ed6b5f01d32d:ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
병합이 진행되면서 불필요한 코드가 추가된 것 같습니다. 삭제해주세요!

2022-12-02 00:43 UTC, sangwoong03 commented on ParkJInjoo/db/migrations/20221129065150_create_users_table.sql
> +>>>>>>> 1cbc1d8fff979e9fb03058b6b4c3ed6b5f01d32d:ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
병합이 진행되면서 불필요한 코드가 추가된 것 같습니다. 삭제해주세요!

2022-12-02 00:43 UTC, sangwoong03 commented on ParkJInjoo/db/migrations/20221129065150_create_users_table.sql
> +>>>>>>> 1cbc1d8fff979e9fb03058b6b4c3ed6b5f01d32d:ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
병합이 진행되면서 불필요한 코드가 추가된 것 같습니다. 삭제해주세요!

2022-12-02 08:33 UTC, lolo-park commented
![스크린샷 2022-12-02 오후 5 32 14](https://user-images.githubusercontent.com/117656236/205250192-078f821c-345b-418f-ab97-43a4a90f1641.png)

멘토님.. 확인부탁드립니다!
db 파일들은 gitignore에 넣어서 안보이는 것 같은데, 
텅텅 비어있는 db/migrations 폴더와 비어있는 migration 파일이 
삭제가 안됩니다

2022-12-03 12:58 UTC, sangwoong03 approved these changes
db/migration 파일 확인해주세요!

2022-12-03 12:58 UTC, merged