[40기 - 김영석] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/40-backend-westagram-1 pull request #2
Opened 2022-11-23 07:43 UTC by yyeongseok

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
 express API 초기 세팅

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-23 08:07 UTC, kyeongraekim commented
이번 과제는 Westagram (인스타그램의 미니 플랫폼 버전)을 작성해주시는 프로젝트 입니다. 책-작가 관련 내용이 아닌 westagram 과제 내용을 아래 링크를 참고해서 재푸시해주세요!~

https://study.wecode.co.kr/session/117

2022-11-25 06:52 UTC, sangwoong03 requested changes

2022-11-25 06:52 UTC, sangwoong03 commented on kimyeongseok/db/schema.sql
> +
schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

`git rm --cached "filename"` 이후 다시 push 해주세요!

2022-11-25 06:52 UTC, sangwoong03 commented on kimyeongseok/db/migrations/20221123131836_create_users_table.sql
> +);
name이 유저의 이름인 경우 동명이인에 의해 특정 유저 정보를 정확히 가려낼 수 없을 것 같습니다.

중복이 되지 않은 `email`이나 `account` 컬럼 등을 추가하여 관리하는 것이 더 좋을 것 같습니다!

보통 이메일은 중복이 불가능한 데이터이기 떄문에 unique 속성을 추가하여 컬럼을 지정합니다.

해당 내용 수정해주세요~!

2022-11-28 04:48 UTC, sangwoong03 requested changes
영석님 현재 또 다른 `db`폴더가 `kimyeongseok` 폴더 외부에도 존재합니다.

해당 폴더는 삭제하고 다시 push 해주세요!

이미 push된 `schema.sql ` 파일의 깃 캐시를 삭제하는 방법이 어렵다면 질문주세요!

2022-11-28 04:48 UTC, sangwoong03 commented on kimyeongseok/db/schema.sql
> +
해당 리뷰가 반영이 되지 않은 것 같네요~! 다시 적용해보시고 잘 되지 않으면 질문해주세요!

2022-11-28 07:54 UTC, closed without merging