[40기 정재헌]Assignment3:Express-API 유저 게시글 등록하기
wecode-bootcamp-korea/40-backend-westagram-1 pull request #5
Opened 2022-11-24 04:39 UTC by JasonJeongjaeheon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- DB 컬럼명 수정
- DB 컬럼명 수정에 따른 관련 코드 수정
- UNIQUE 부여
- end point 중복 제거
- schema.sql .gitignore 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- DB table에서 이미 users라고 명시되어 있으므로, column명에서 user를 삭제
- 수정된 DB table column 명에 맞추어 해당 코드 부분 수정
- users table에서 email 중복을 피하기 위해 UNIQUE 부여
- END POINT 중복 요소 제거 : POST '/ users/create -> POST '/users'로 수정
- schema.sql .gitignore 추가 완료

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 아직 git 환경에 대한 이해가 너무 부족함
- Database에 저장될 데이터들에 대한 추가적인 공부가 필요

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-24 05:29 UTC, kyeongraekim requested changes

2022-11-24 05:29 UTC, kyeongraekim commented on JeongJaeHeon/app.js
> +        console.log("Data Source has not been initialized")
"error message" 에러 메세지는 보다 명확히 작성하면 더 가독성이 좋아지고 직관적이 되겠네요!
Failed to initialize datasource 정도가 첫 단어부터 그 의미가 명확하고 긍정에서의 메세지와 다름이 눈에 띄어서 좋은 에러메세지가 될 것 같습니다!~

2022-11-24 05:29 UTC, kyeongraekim commented on JeongJaeHeon/app.js
> +app.use(morgan('combined'));
- 개발 환경에 맞는 morgan을 위해서 dev 나 tiny로 수정해서 올려주세요!~

2022-11-24 05:29 UTC, kyeongraekim commented on JeongJaeHeon/app.js
> +    res.status(201).json({message : 'pong'});
- ping-pong 은 아주 간단한 get 요청으로 시험하는 네트워크의 health check 임으로 상태코드를 200으로 수정해주세요!~

2022-11-24 05:29 UTC, kyeongraekim commented on JeongJaeHeon/app.js
> +app.post('/users/create', async (req, res, next) => {
- 매개변수로 선언한 next는 미들웨어로서 사용할 때 필요합니다. 해당 함수는 클라이언트에게 바로 제이슨 리턴을 전달하는 기능을 함으로 굳이 next까지 불러들어올 필요는 없어 보이네요!
- post그 자체로도 이미 create의 의미가 잘 담겨있음으로 RESTful 한 엔드포인트 설계법에 의거하여서 create라는 또다른 불필요한 동사어구를 삭제해주세요!~

2022-11-24 05:29 UTC, kyeongraekim commented on JeongJaeHeon/db/migrations/20221124005146_create_users_posts_tables.sql
> +CREATE TABLE users_posts (
- 해당 내용은 users_posts의 중간테이블의 역할을 하는 좋아요 기능을 함축하는 테이블로서 보여지는데, 따라서 likes 정도로 수정하는게 더 의미면에서 직관적으로 도움이 될 것 같습니다.
- 추가로 한명의 유저가 동일 게시글의 중복의 좋아요를 하지못하도록 막을 수 있게 다음의 코드를 한번 살펴보시고 고민하신 후에 추가해주세요!
```javascript
ALTER TABLE likes ADD CONSTRAINT constraint_likes_unique UNIQUE (user_id, post_id);
```

2022-11-24 05:29 UTC, kyeongraekim commented on JeongJaeHeon/db/schema.sql
> +/*!40101 SET @saved_cs_client     = @@character_set_client */;
- schema 파일은 개인이 관리하는 기록물임으로 깃이그노어에 추가해서 깃헙에서 공유가 되지 않도록 수정해주세요!

2022-11-24 05:29 UTC, kyeongraekim commented on gildong/app.js
> +    .catch(() => {console.log("Data Source has not been initialized")})
예시 폴더인 "길동"에 불필요한 코드들이 들어간 것 처럼 보이는데 다시 한번 확인해주세요!

2022-11-29 01:15 UTC, sangwoong03 requested changes

2022-11-29 01:15 UTC, sangwoong03 commented on JeongJaeHeon/app.js
> +})
게시글에 대한 수정 요청이 있은 후 수정된 게시글을 다시 반환하는 api를 작성해주셨는데 너무 잘 작성해주셨습니다!

다만 몇가지 수정 사항이 있다면,

- 수정의 대상이 되는 `postId` 도 요청에서 전달해주어야 하는 정보 중 하나가 되어야 할 것 같습니다~!
- 수정된 게시글을 불러오는 쿼리문에서는 `posts` 테이블에서 받아오되 users 테이블을 결합하여 수정 요청을 한 유저의 게시글을 받아올 수 있도록 수정해주세요!

```suggestion
app.patch('/posts/:postId', async(req, res) => {
    const { postId } = req.params
    const { userId, title, content } = req.body
    
    await mysqlDataSource.query(
        `UPDATE
            posts p
          SET
            p.title = ?,
            p.content = ?
        WHERE p.id = ?
        ` [ title, content, postId ],);

    const post= await mysqlDataSource.query(
        `SELECT
            u.id AS userId,
            u.profileimage AS userProfileImage,
            p.id AS postingId,
            p.title As postingTitle,
            p.content AS postingContent
          FROM posts p
          JOIN users u ON p.user_id = u.id
          WHERE p.user_id = ?;
        `, [ userId ]) 
     res.status(200).json(post) 
})
```

2022-11-29 01:15 UTC, sangwoong03 commented on JeongJaeHeon/app.js
> +})
path parameter로 받아올 수 있을 것 같습니다!

```suggestion
app.delete('/posts/:postId', async(req, res) => {
    const { postId } = req.params

    await mysqlDataSource.query(
        `DELETE FROM posts p
          WHERE p.id=?
        `, [postId]
    )
    res.status(204).json({message : 'posting Deleted'})
})
```

2022-11-29 01:15 UTC, sangwoong03 commented on JeongJaeHeon/db/migrations/20221127020501_create_posts_tables.sql
> +ALTER TABLE posts ADD imageurl VARCHAR(1000) NOT NULL
컬럼명을 `image_url`으로 작성해주면 좀 더 명확할 것 같습니다!

2022-11-29 01:15 UTC, sangwoong03 commented on JeongJaeHeon/db/migrations/20221128043842_create_posts_tables.sql
> +ALTER TABLE posts ADD imageurl VARCHAR(2000) NOT NULL UNIQUE
해당 컬럼에 unique 속성을 추가한 이유가 있나요?

2022-11-29 01:15 UTC, sangwoong03 commented on JeongJaeHeon/db/schema.sql
> +/*!40101 SET @saved_cs_client     = @@character_set_client */;
해당 부분도 다시 확인하여 수정해주세요!

2022-11-29 01:15 UTC, sangwoong03 commented on gildong/app.js
> +    .catch(() => {console.log("Data Source has not been initialized")})
gildong 폴더에 있는 파일 삭제해주세요!

2022-11-29 02:09 UTC, JasonJeongjaeheon commented on JeongJaeHeon/db/migrations/20221128043842_create_posts_tables.sql
> +ALTER TABLE posts ADD imageurl VARCHAR(2000) NOT NULL UNIQUE
해당 컬럼에 unique 속성 추가는 실수로 추가하였습니다. 수정하겠습니다..!

2022-11-29 04:55 UTC, sangwoong03 requested changes

2022-11-29 04:55 UTC, sangwoong03 commented on JeongJaeHeon/app.js
> +})
엔드포인트는 특정 기능이 담길 수 있도록 작성해주면 됩니다!

지금 작성해주신 부분도 좋지만 좋아요는 사실 로그인을 할 수 있는 기능이고, 추후 이 부분에 대해서 로그인을 확인하는 모듈을 작성해볼 수 있습니다.

그렇기에 다음과 같이 수정할 수 있습니다.

```suggestion
app.post('/likes', async(req, res) => {
    const { userId, postId } = req.body

    await mysqlDataSource.query(
        `UPDATE likes
          SET 
            user_id = ?, 
            post_id = ? 
          `, [ userId, postId ])
    res.status(200).json({message : "likes Created"})
})
```

2022-11-30 01:20 UTC, sangwoong03 requested changes

2022-11-30 01:20 UTC, sangwoong03 commented on .prettierrc
> +}
해당 프리티어 파일도 삭제해주세요~!

2022-11-30 05:38 UTC, kyeongraekim requested changes

2022-11-30 05:38 UTC, kyeongraekim commented on JeongJaeHeon/db/migrations/20221128013747_create_users_tables.sql
> +ALTER TABLE users ADD CONSTRAINT users_email_ukey
현재 alter table, 즉 수정을 의미하는 migration 파일들의 파일명이 전부 create_user 라고 되어있습니다. 이러한 경우에 파일명을 update_user 로 해주셔야 다른 개발자들의 혼선을 막아줄 수 있습니다.

2022-12-01 00:39 UTC, sangwoong03 approved these changes
LGTM 👍

2022-12-01 00:40 UTC, merged