[40기 - 윤형준] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/40-backend-westagram-1 pull request #7
Opened 2022-11-24 06:57 UTC by hysy9255

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- API Express 초기 설정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- /ping 앤드 포인트에서 Get request 시 "{message:pong}" 반환으로 응답하게 구현 
- 서버 가동 코드 작성
- TypeORM을 통해 MySQL DB와 연동

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-24 07:15 UTC, sangwoong03 requested changes
형준님~ 첫 초기세팅임에도 잘 수행해주셨습니다!

커멘트 천천히 읽어보시고 수정해주세요~!

2022-11-24 07:15 UTC, sangwoong03 commented on hyungjoonYoon/.env.sample
> +TYPEORM_LOGGING =TRUE
해당 정보를 통해 외부, 제 3자에게 노출되었을 때 데이터베이스 내부 정보가 유출될 가능성이 높습니다.

다른 개발자가 해당 프로젝트에 참여하여 동일한 `.env` 파일을 구성할 수 있도록 명시해주는 역할을 하는 파일입니다. 

`sample`이라는 파일명과 부합하도록 수정해주세요!
```suggestion
TYPEORM_CONNECTION = RDBMS_TYPE
TYPEORM_HOST = HOST_NUMBER
TYPEORM_USERNAME = USERNAME
TYPEORM_PASSWORD = PASSWORD
TYPEORM_DATABASE = DATABASE_NAME
TYPEORM_PORT = PORT_NUMBER
TYPEORM_LOGGING = BOOLEAN
```

2022-11-24 07:15 UTC, sangwoong03 commented on hyungjoonYoon/app.js
> +const { DataSource } = require("typeorm");
- 모듈 import 순서
    - import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
    - 다음과 같은 순서로 import 해줍니다.
        - Bulit-in 패키지
        - 3rd-party 패키지
        - custom 패키지
        
        ```jsx
        //// Built-in package
        const http = require('http')
        
        //// 3rd-party package
        require('dotenv').config();
        const express = require('express');
        const cors    = require('cors');
        const morgan  = require('morgan');
        const { DataSource } = require('typeorm');
        
        //custom package
        const api = require('./../api')
        
        const app = express();
        ```

위의 예시 코드를 참고하여 수정해주세요!
불필요한 주석은 포함하지 않아도 됩니다!

2022-11-24 07:15 UTC, sangwoong03 commented on hyungjoonYoon/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

`git rm --cached` 명령어에 대한 학습을 해볼 수 있는 기회입니다.

2022-11-24 07:15 UTC, sangwoong03 commented on hyungjoonYoon/package.json
> +  }
dependecies와 devDependencies의 차이점에 대해 학습해주세요!

배포 단계에 반드시 필요한 패키지/모듈이 있는 반면, 개발 단계에서만 필요한 패키지/모듈이 존재합니다.

이 둘의 차이점을 명확히 알고 아래의 명령어를 통해 수정해주세요!

npm install "package-name"
npm install --save-dev "package-name"
npm uninstall "package-name"

```suggestion
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "mysql": "^2.18.1",
    "typeorm": "^0.3.10"
  },
  devDependencies: {
      "morgan": "^1.10.0",
      "nodemon": "^3.0,0"
  }
```

2022-11-24 07:15 UTC, sangwoong03 commented on hyungjoonYoon/db/migrations/20221122152112_users.sql
> +);
회원가입 시 유저 정보 중 중복되면 안되는 데이터를 저장해야하는 경우가 있습니다.

따라서 unique contraint를 추가해주셔야 합니다.

```suggestion
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
		name VARCHAR(50) NOT NULL,
		email VARCHAR(200) NOT NULL,
		profile_image VARCHAR(1000) NULL,
		password VARCHAR(200) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
		CONSTRAINT users_email_ukey UNIQUE (email)
		PRIMARY KEY(id)
);
```

2022-11-24 07:15 UTC, sangwoong03 commented on hyungjoonYoon/db/migrations/20221122152121_likes.sql
> +);
좋아요 기능은 특정 유저가 한번 좋아요를 눌렀을 때 취소가 되는 기능이 표함되어 있습니다.

특정 유저가 이미 좋아요 버튼을 눌렀다는 정보를 unique 속성을 추가하여 관리할 수 있습니다.

위에서 언급한 내용을 적용하여 수정해주세요!

2022-11-26 12:38 UTC, hysy9255 commented
리뷰 감사합니다! `commit id: c5a6aae` 에 추가로 변수명 수정하여 반영하였습니다.

2022-11-26 12:53 UTC, closed without merging