[40기-박진주]Assignment1:Express API-초기 환경 세팅
wecode-bootcamp-korea/40-backend-westagram-1 pull request #8
Opened 2022-11-24 07:38 UTC by lolo-park

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-25 00:14 UTC, sangwoong03 requested changes
진주님 고생하셨습니다!

2022-11-25 00:14 UTC, sangwoong03 commented on ParkJInjoo/package.json
> +  }
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.
```suggestion
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "mysql2": "^2.3.3",
    "typeorm": "^0.3.10"
  },
  devDependencies: {
      "morgan": "^1.10.0",
      "nodemon": "^2.0.20"
  }
```

2022-11-25 00:14 UTC, sangwoong03 commented on ParkJInjoo/app.js
> +const { DataSource } = require("typeorm");
- 모듈 import 순서
    - import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
    - 다음과 같은 순서로 import 해줍니다.
        - Bulit-in 패키지
        - 3rd-party 패키지
        - custom 패키지
        
        ```jsx
        //// Built-in package
        const http = require('http')
        
        //// 3rd-party package
        require('dotenv').config();
        const express = require('express');
        const cors    = require('cors');
        const morgan  = require('morgan');
        const { DataSource } = require('typeorm');
        
        //custom package
        const api = require('./../api')
        
        const app = express();
        ```
```suggestion
const http = require("http");

require("dotenv").config()
const express = require("express");
const cors = require("cors");
const morgan = require("morgan");
const { DataSource } = require("typeorm");

app = express();

app.use(express.json());
app.use(cors());
app.use(morgan("combined"));
```

2022-11-25 00:21 UTC, sangwoong03 commented on ParkJInjoo/app.js
> +const myDataSource = new DataSource({
myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2022-11-25 06:41 UTC, sangwoong03 requested changes

2022-11-25 06:41 UTC, sangwoong03 commented on ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
> +  email VARCHAR(200) NOT NULL,
회원정보는 중복이 되어서는 안되는 데이터가 존재합니다.

보통 웹 사이트에서 회원가입을 할 때 이메일을 입력하고 중복확인이라는 버튼을 누르죠!

이런 기능을 포함하기 위해 email 컬럼에 unique 속성을 추가해주세요!

`CONSTRAINT 제약조건 UNIQUE (email)`에 대한 키워드로 제약조건, unique에 대한 자료를 찾아본 후 적용해주세요!

2022-11-26 12:27 UTC, hysy9255 commented on ParkJInjoo/app.js
> +const { DataSource } = require("typeorm");
안녕하세요 상웅님! 진주님께 해주신 리뷰에서  suggested change를 보다가 `const http = require("http");`를 위에 추가해주신 것을 확인하였는데, 이 http 모듈이 꼭 필요한 것인가요? express 프레임워크가 http 모듈을 대체하는 것 아닌가요?

2022-11-28 08:39 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-28 08:39 UTC, merged